[package]
name = "SQL-injection-vulnerability-in-WHERE-clause-allowing-retrieval-of-hidden-data"
version = "0.1.0"
edition = "2024"

[dependencies]
reqwest = "0.12.24"
scraper = "0.24.0"
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }
urlencoding = "2.1.3"
